### PR TITLE
1.05b

### PR DESCRIPTION
**Pull request by fashberg**
Hi Klaus!

First of all: thank you for your great work on this project.
Just because of the availability of an open source alternative i've bought and installed 5 of that beca thermostats.
I've did some improvements:
* mqtt topic separation between cmnd and stat
** device->lastStateWaitForResponse is no longer required - probably this is the cause of all the mqtt problems we can see in the current discussion.
** home assistant does no longer receives it’s own messages and vice versa.
** example: HASS requests home/room/things/thermostat/properties and sets some values it’s receives the same messages and thinks it is a status update. But many parameters are missing in that message and are changing then to unknown
* for HASS I’ve added the parameter ‘mode’ which combines device on/off and schedule on/off into a single parameter.

I’m very interested what you’re thinking about.

Kind Regards from Munich

Folke

### CODE REVIEW

**Comment by austwhite** [comment]
Watching this as I am interested in easier HA integration as that is what I use.
In your version, do you have any issues with MQTT dropping/not responding after a few hours?
I have that issue with 1.0 noting I didn't seem to have it in 0.9x

**Comment by fashberg** [comment]
> Watching this as I am interested in easier HA integration as that is what I use.
> In your version, do you have any issues with MQTT dropping/not responding after a few hours?
> I have that issue with 1.0 noting I didn't seem to have it in 0.9x.
> Also, have you had any luck adding the Auto-discovery to utilise HA areas and integrations?

I've never used something else then 1.00. After some time sometimes controlling was not longer possible. No replies from Beca. This works now as expected - until now. Tested 3 days.
Formerly HASS received it's own messages, beause of same topic, probably triggering endless automation loops.
Have to see if everything is fine.

See how easy is HASS setup now: https://github.com/fashberg/WThermostatBeca#integration-in-home-assisant

**Comment by austwhite** [comment]
Thanks for the reply.
I'll try your one soon and see how it goes.

**Comment by austwhite** [comment]
I have tried your code and it does solve the MQTT no response issue.
Now I just have to work out the line to determine heating/idle as I have done the hardware mod to allow status to be shown

**Comment by nimda5** [comment]
Scheduler: wrong MQTT returned on empty payload.
I think it's existing bug, but report to you:
requesting mqtt `<your_topic>/cmnd/things/thermostat/schedules` with empty payload suppose to return json to the `<your_topic>/stat/things/thermostat/schedules`
but returned to `<your_topic>/stat/things/thermostat/`**properties**

**Comment by austwhite** [comment]
@fashberg  Any chance, in 1.01b, that you could make a modification to the MQTT delay when temperature is set manually on the thermostat?

Example:  If I change the thermostat manually from say 28 to 27, but the house is still at only 25 (so heat mode doesnt change) it will take 4 minutes before the new temperature is sent via MQTT to update Home Assistant.

I am not good enough with my programming to see if this is workable without hammering the NTP servers.

**Comment by Nordicfastware** [comment]
Tested 1.01b for a few hours trying to mistreat it by sending all sorts of cmnd both physical and over mqtt and it works. Pretty good update, with a much easier integration in my Home Assistant.

However as many others I find that the update interval is too long, with the issue that if you change on the panel there is 5 minutes window or less where it is in conflict with mqtt stat.
Workaround: I created an automation which publishes:"home/room/cmnd/things/thermostat/properties" 
with no payload every x seconds to reduce this window.
Would be nice to have a payload sent by the device as soon as you change something and ideally an ability to change the standard refresh time on the  webUI at http://192.168.X.XXX/thermostat?

All in all this pull request should be implemented. And the above can be on future commits if decided.

**Comment by austwhite** [comment]
@fashberg I think this is stable enough to be its own version without the beta prefix.
If you could change the delay from 5 minutes to 1 minute that would be good, but I am not sure whether that would cause it to hammer the NTP server with the way it's written.
Is that worth looking at?  If not, I can live with the slight delay as when the heat kicks in or out it sends an update anyway.
100% the separation of the topics fixed the MQTT freezing issue.

**Comment by realthk** [comment]
Hi Folke, 
this is great news!
I use Nodered just to separate topics, and this can be avoided with your version.

Could you perhaps check [issue #62](https://github.com/klausahrenberg/WThermostatBeca/issues/62)?
I wonder if the MCU sends info about manual temperature setting change to the ESP, so we could receive MQTT message at once? Then this device could be used not only as a thermostat, but also as a control interface for another thermostat implemented in Home Assistant software.

**Comment by martonmodis13** [comment]
Hi everyone!
Is anyone planning to be able to set the system and fan mode with mqtt?
Currently if I change the fanmode or the systemmode in Ha I can't set the correct mode on the thermostat.

Thanks,

**Comment by nimda5** [comment]
@fashberg - thanks for you work. Can you please fix stat command for scheduler.
I posted problem [https://github.com/klausahrenberg/WThermostatBeca/pull/81#issuecomment-598461168](url), My very ugly fix is in WBecaDevie.h ~367
```
json.endObject();
+ String new_topic = completeTopic.c_str();
+ new_topic.replace("/properties", "/schedules");
+ network->publishMqtt(new_topic.c_str(), response);
- network->publishMqtt(completeTopic.c_str(), response);
lastSchedulesWaitForResponse = true;
```

**Comment by fashberg** [comment]
> @fashberg - thanks for you work. Can you please fix stat command for scheduler.
> I posted problem [https://github.com/klausahrenberg/WThermostatBeca/pull/81#issuecomment-598461168](url), My very ugly fix is in WBecaDevie.h ~367
> 
> ```
> json.endObject();
> + String new_topic = completeTopic.c_str();
> + new_topic.replace("/properties", "/schedules");
> + network->publishMqtt(new_topic.c_str(), response);
> - network->publishMqtt(completeTopic.c_str(), response);
> lastSchedulesWaitForResponse = true;
> ```

Fixed in 1.03b https://github.com/fashberg/WThermostatBeca/commit/8449acd43b4b74db9fe5b4d23c02c5c0e8c5c2d0
#81 

Thanks!

**Comment by nimda5** [comment]
Thanks, this was fast ;)

**Comment by austwhite** [comment]
Hi @fashberg 
I ran additional testing on 1.03b and have not yet been able to replicate my earlier issue with it freezing.  I'll give it a couple more days.
Have you heard from Klaus as to whether he will implement this as part of his repository or should you take it as your own fork and refine it as a separate thing?

**Comment by rengaboy** [comment]
Hello everyone.
I have small issue with this firmware. Some of the fields in json ("shedulesMode","mode", "state") are quoted, and some are not ("ecoMode", "locked"). This formatting causes a problem in HASS mqtt_switch, i need to specify payload with quotes, and state without.
`- platform: mqtt
  name: "Hall thermostat eco mode"
  state_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  value_template: "{{ value_json['ecoMode'] }}"
  command_topic: "homeassistant/beca/hall/cmnd/things/thermostat/properties/ecoMode"
  payload_on: "true"
  payload_off: "false"
  state_on: true
  state_off: false`
If all fields wiil be with quotes, there will be no need to specify state_on and off, payload will be enough.

**Comment by austwhite** [comment]
I think that is done in the original firmware also.
I don't use the lock mode, but got away mode to work pretty easily.
What would be ideal, down the track, if a Home Assistant Auto Discovery could be written into it so it shows up in the integration list.

**Comment by austwhite** [comment]
hi @fashberg 
Would it be possible to have a Home Assistant auto-discovery added to this firmware?
Documentation is [here](https://www.home-assistant.io/docs/mqtt/discovery/) .
Maybe it can be selectable in the settings page. 
I was thinking this may be worth while as Home Assistant is the most popular OpenSource home control software hub and there does seem to be a lot of HA users asking questions.
Also, it would be nice for it to show up properly under the MQTT integration to select areas and more easily integrate to automations in HA.

I do already appreciate all the work you've put in and i understand if this is a little too much to ask for.

**Comment by iMike78** [comment]
> 
> 
> hi @fashberg
> Would it be possible to have a Home Assistant auto-discovery added to this firmware?
> Documentation is [here](https://www.home-assistant.io/docs/mqtt/discovery/) .

Well, this is a very good idea, as this is a popular and cheap smart thermostat. Not too difficult to flash, and easy to do the hardware mod. I'm using two of these thermostats with Home Assistant.
At this point I have a question. Still I'm using the 1.0fw on my HW modded thermostats. With the 1.03b can I leave the node-red flows? Will everything work through MQTT (I mean all the topics are exact, and the states are reported)?

**Comment by austwhite** [comment]
1.01b and above by @fashbwrg change the MQTT topics so they are separated.

Instead of state and command topic being the same, which can cause issues for some installations, they are separated.

You  have to change the command topic to be ...../cmnd/things/.....
You also have to change state topic to ...../stat/things/.....

Other than that, it should work similar to 1.00 but with quicker updates

**Comment by iMike78** [comment]
> 
> @iMike78
> 1.01b and above by @fashberg change the MQTT topics so they are separated.
> 
Thank you for your answer, it's a good news. Then I'll wait for his answer about the HA integration.

**Comment by austwhite** [comment]
@iMike78
I don't use Node Red, but if you want to try 1.03b (I am using it at the moment)
I can paste the yaml I use in configuration.yaml

**Comment by iMike78** [comment]
> 
> 
> @iMike78
> I don't use Node Red, but if you want to try 1.03b (I am using it at the moment)
> I can paste the yaml I use in configuration.yaml

Is your thermostat hardware modded? I mean do you have state report (heating/idle) as well?

**Comment by rengaboy** [comment]
@iMike78 
I have HA integration on 1.03b.
`
- platform: mqtt
  name: Hall Thermostat
  payload_on: "true"
  payload_off: "false"
  temperature_command_topic: "homeassistant/beca/hall/cmnd/things/thermostat/properties/targetTemperature"
  temperature_state_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  temperature_state_template: "{{ value_json['targetTemperature'] }}"
  current_temperature_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  current_temperature_template: "{{ value_json['temperature'] }}"
  mode_command_topic: "homeassistant/beca/hall/cmnd/things/thermostat/properties/mode"
  mode_state_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  mode_state_template: "{{ value_json['mode'] }}"
  action_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  action_template: "{{ value_json['state'] }}"
  modes:
    - "heat"
    - "auto"
    - "off"
  min_temp: 15
  max_temp: 35
  temp_step: 0.5
  precision: 0.5
`
And two seperate switches for Lock mode and EcoMode.
`
- platform: mqtt
  name: "Hall thermostat eco mode"
  state_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  value_template: "{{ value_json['ecoMode'] }}"
  command_topic: "homeassistant/beca/hall/cmnd/things/thermostat/properties/ecoMode"
  payload_on: "true"
  payload_off: "false"
  state_on: true
  state_off: false

- platform: mqtt
  name: "Hall thermostat locked"
  state_topic: "homeassistant/beca/hall/stat/things/thermostat/properties"
  value_template: "{{ value_json['locked'] }}"
  command_topic: "homeassistant/beca/hall/cmnd/things/thermostat/properties/locked"
  payload_on: "true"
  payload_off: "false"
  state_on: true
  state_off: false
`

**Comment by austwhite** [comment]
@iMike78
Yes.  I have the hardware mod done and get heating/idle

**Comment by iMike78** [comment]
@austwhite 
Thank you. Then I will give a try on one of my thermostat. :) 
But still would be great if we could have the autodiscovery or add an integration option.

**Comment by austwhite** [comment]
@iMike78 
here is my Yaml.    You will just put this under `climate: `
@rengaboy when pasting code, can you use the <> button at the top of the edit window to format it

```
  - platform: mqtt
    name: Central heating
    temperature_command_topic: "home/centralheat/cmnd/things/thermostat/properties/targetTemperature"
    temperature_state_topic: "home/centralheat/stat/things/thermostat/properties"
    temperature_state_template: "{{ value_json['targetTemperature'] }}"
    current_temperature_topic: "home/centralheat/stat/things/thermostat/properties"
    current_temperature_template: "{{ value_json['temperature'] }}"
    away_mode_command_topic: "home/centralheat/cmnd/things/thermostat/properties/ecoMode"
    away_mode_state_topic: "home/centralheat/stat/things/thermostat/properties"
    away_mode_state_template: "{{ value_json['ecoMode'] }}"
    payload_on: "true"
    payload_off: "false"
    mode_command_topic: "home/centralheat/cmnd/things/thermostat/properties/mode"
    action_topic: "home/centralheat/stat/things/thermostat/properties"
    action_template: >
      {% if value_json.state == 'heating' %}
      heating
      {% elif value_json.mode == 'off' %}
      off
      {% else %}
      idle
      {% endif %}
    mode_state_topic: "home/centralheat/stat/things/thermostat/properties"
    mode_state_template: "{{ value_json['mode'] }}"
    modes:
      - "heat"
      - "auto"
      - "off"
    min_temp: 5
    max_temp: 35
    temp_step: 0.5
    precision: 0.5
```

**Comment by rengaboy** [comment]
@austwhite Of course i use it. It never worked for me.

**Comment by austwhite** [comment]
@rengaboy 
I actually like your approach using a separate switch for away and lock modes.
It seems neater and easier to use than integrating with the thermostat.
Do you get the idle/heating status show with your yaml?

**Comment by rengaboy** [comment]
> @rengaboy
> I actually like your approach using a separate switch for away and lock modes.
> It seems neater and easier to use than integrating with the thermostat.
> Do you get the idle/heating status show with your yaml?

Sure. States is in the action topic.

**Comment by austwhite** [comment]
@rengaboy 
Ahh.  I see you use the states and it just switches between heating and off.
Thats why I used the few extra lines in script so I get  heating, idle and off (idle is when the thermostat is on, but heating is not being called).

**Comment by nimda5** [comment]
@fashberg thanks for your great job. I don't know why @klausahrenberg didn't merge your changes. More easy to integrate.. I use OpenHab and integration was a lot more easier than same topics. I created  TZ fix for your fork, but new device didn't arrived yet for testing. I don't need to test my hacks anymore, will use your pretty fixes ;) 
P.S. @klausahrenberg  please merge :)

**Comment by austwhite** [comment]
Maybe we need to branches.
The original by Klaus and this one and just keep them as two branches.

**Comment by klausahrenberg** [comment]
> P.S. @klausahrenberg please merge :)
Hi, yes, I know. Please give me some time to review the changes. I worked not on this project since December. As I can see, MQTT topics are splitted for getting and setting for Home Assistant. I don't use HA - so I don't have the difficulties so far. Moreover, if I merge directly - I will maybe break my current configuration. Please understand. I'm thinking about a configurable option for MQTT topics that reflects both needs.

**Comment by austwhite** [comment]
@klausahrenberg
I think configurable MQTT topics would be ideal.

**Comment by nimda5** [comment]
@klausahrenberg  Ok, sorry I was thinking you don't want to merge, just sometimes happens when somebody else modify your code ;) I'm too not using HA, and on the OH (2.3). And was more easy to migrate to the different topics, than fighting conflicts with same topic name. I think @fashberg can do it, he is so fast and almost bug free ;)

**Comment by austwhite** [comment]
I had an issue with 1.05b that bricked my esp device in the thermostat.
Not sure what happened.
All previous versions were flawless.
I'll open it up and try a manual flash soon.

**Comment by klausahrenberg** [comment]
> I had an issue with 1.05b that bricked my esp device in the thermostat.

I think, the brick has other reasons, I tested the v1.05b from @fashberg now and it works fine. There are a lot of things I like in this version: Schedules configurable via web interface is great and also the time zone/DST calculation is great without worldtimeapi. However, I can not merge the projects right now. The version 1.05b breaks the Mozilla Webthing support because the configuration page is there directly available under http://<device_ip> and not like in my version http://<device_ip>/config. I know, my solution is ugly for someone, who don't use Webthings - but Webthings can only work if the configuration of device in json is available under http://<device_ip>

**Comment by austwhite** [comment]
@Klausahrenberg
I agree the bricking has another reason.
Maybe this version (1.05) can have its own branch separate from the main We things branch?

**Comment by fashberg** [comment]
Hi Klaus,

great to hear from you.

> The version 1.05b breaks the Mozilla Webthing support because the configuration page is there directly available under http://<device_ip> and not like in my version http://<device_ip>/config. I know, my solution is ugly for someone, who don't use Webthings - but Webthings can only work if the configuration of device in json is available under http://<device_ip>

i've installed webthings and did some test to not break up. I've change MDNS to this URL (/things appended)
```
MDNS.addServiceTxt("http", "tcp", "url", "http://" + mdnsName + "/things");
```
Worked fine for me. 
Now i see it stopped working. WebThings GW Outputs:
webthings-gateway | 2020-04-01 12:50:35.961 INFO   : thing-url-adapter: Failed to parse description at http://10.10.200.69/things: SyntaxError: Unexpected end of JSON input

The json output stopped in the middle. I've increased #define SIZE_JSON_PACKET to 2048 and now WebThings + autodiscovery is working again :) Buffer was to small.

See 1.06b - your webthings should work again

MQTT: I thing you must break with the single topic at MQTT. It solved nearly all mqtt problems.
Without separation neither home-assistant or other software nor the beca device itself are able to check if a message is a request or a response. If you request targetTemperature you'll get an answer even if beca is off - because you'll get your own message back. Then you may or may not get beca's answer.

See tasmota or other mqtt devices - separated topics is how MQTT work.
I think it's fine for the users to change MQTT topics on upgrade - you'll get a stable communication in exchange ;)

@austwhite hm, interesting. the only changes between 1.04/1.05 was sending updates to MCU for systemMode/fanMode - only a feature for heating/cooling gevices.

Hope you get it to work - please respond if you need support

Kind Regards

Folke

**Comment by klausahrenberg** [comment]
> I've increased #define SIZE_JSON_PACKET to 2048 and now WebThings

@fashberg, great to hear from you, too. Please be aware that increasing the buffer is a risky thing on these devices and I had several sleepless nights to reduce the MQTT/JSON buffers, to reduce String objects, wrote thin JSON parser and so on. The magical size for the buffer was around 1100 byte. Above this value the ESP will crash from time to time (if the ESP crashes you will notify it because the background LCD of thermostat is on during restart). My solution was to keep any buffer at lowest possible size.
I like your improvements and will merge it as soon as possible. Thanks.

**Comment by fashberg** [comment]
@klausahrenberg 
Yes, not much space.  We should add uptime to things/clock, than we can track reboots (logged to mqtt).
I for got a "delete page" and after 10 reloads the esp bootet. Yes. But it looks not bad after some hours 

What about rebasing on my work and Platform.IO structure?
It's hard to compare our releases (1.01/1.06b) because you moved all files to src/ in a way git could not track.
Also you cannot compare your revisions 1.00 <-> 1.01/

My git repo has tracked all your old changes:
2020-04-01_13h56_23

removing 1.01, switch back to 1.00 and accept all incoming changes from me.
Your timezone fix is not longer required and the changes with the MQTT-Group can be done easily on top of 1.06b

Grüße aus München
Folke

**Comment by klausahrenberg** [comment]
Hi, I will merge tomorrow in your proposed way. I had some other fixes from 1.00 to 1.01, which I will take over. But I think, I will go back to 1.00, merge and reimplement my fixes. But here it's already late, after 9pm. Schöne Grüße aus Seoul.

**Comment by klausahrenberg** [comment]
Cannot merge automatically anymore. Will merge manually

**Comment by fashberg** [comment]
Moin @klausahrenberg !

git ist manchmal etwas kompliziert.  :)

I've tested it for you - you don't need to make the pseudo repo.


1) create branch at your 1.00
2) switch to the branch and make it new master, reverting 
3) now you can pull my master (1.06b)
4) push it

# new clone of your repo as pseudo remote (so i can test push)
git clone https://github.com/klausahrenberg/WThermostatBeca.git WThermostatBeca.remote
# make it a bare-repo (like github)
cd WThermostatBeca.remote
git config core.bare true
cd .. 
# clone pseudo github it again
git clone WThermostatBeca.remote WThermostatBeca

# start here
cd WThermostatBeca
git remote get-url origin
## C:/Users/folke/Documents/Arduino/thermostat-test/WThermostatBeca.remote


# create branch at your version 1.00 called 1.00 and checkout
git branch  "1.00" 2df063b09bcd5a56616c81802e1ade4b8fc4e5db
git checkout 1.00

# upload to remote
git push --set-upstream origin 1.00


# https://stackoverflow.com/questions/2763006/make-the-current-git-branch-a-master-branch
git merge --strategy=ours master 
git checkout master
git merge 1.00
 
 

# pull my master
git remote add fashberg https://github.com/fashberg/WThermostatBeca.git
git pull fashberg master
# -> all get's merged properly


git push
 
 
 same for wadapter
 ----------------------------
 
 

# new clone of your repo as pseudo remote (so i can test push)
git clone https://github.com/klausahrenberg/WAdapter.git WAdapter.remote
# make it a bare-repo (like github)
cd WAdapter.remote
git config core.bare true
cd .. 
# clone pseudo github it again
git clone WAdapter.remote WAdapter


# start here
cd WAdapter
git remote get-url origin
## C:/Users/folke/Documents/Arduino/thermostat-test/WAdapter.remote


# create branch at your version 1.00 called 1.00 and checkout
git branch  "1.00" 1146ebcaf6b116298a61d986fc1441889b655431
git checkout 1.00

# upload to remote
git push --set-upstream origin 1.00
 

# https://stackoverflow.com/questions/2763006/make-the-current-git-branch-a-master-branch
git merge --strategy=ours master 
git checkout master
git merge 1.00
 
 

# pull my master
git remote add fashberg https://github.com/fashberg/WAdapter.git
git pull fashberg master
# -> all get's merged properly


git push

**Comment by fashberg** [comment]
ah, more elegant. Then also all the commits with all the binaries in .pio folder are getting deleted - not blowing up the repo 

```
git reset --hard 2df063b09bcd5a56616c81802e1ade4b8fc4e5db
git push --force
git remote add fashberg https://github.com/fashberg/WThermostatBeca.git
git pull fashberg master
git push
````
und entsprechend WAdapter
```
git reset --hard 1146ebcaf6b116298a61d986fc1441889b655431
git push --force
git remote add fashberg https://github.com/fashberg/WAdapter.git
git pull fashberg master
git push
```

**Comment by fashberg** [comment]
> I had an issue with 1.05b that bricked my esp device in the thermostat.
> Not sure what happened.
> All previous versions were flawless.
> I'll open it up and try a manual flash soon.

Hey @austwhite,

is your device back online?

i've had a similar issue on my NodeMCU Debugging Board and an two Becas.
It was in my case not the Firmware but my FritzBox Wifi-AP/Router. Maybe because of mesh settings and automatic handover between my Routers? The AP rejected the connection. After restart of the Wifi-AP the becase could connect to my WLAN.

I've added (1.07-fas) a fallback of thermostat to AP-Mode in case of no connection to configured Network. 

KInd Regards
Folke

**Comment by austwhite** [comment]
I haven't had a chance to play with it yet.
It should come back up though.
Your firmware is really great.

**Comment by fashberg** [comment]
hi @austwhite 
> Would it be possible to have a Home Assistant auto-discovery added to this firmware?
> Documentation is [here](https://www.home-assistant.io/docs/mqtt/discovery/) .
> Maybe it can be selectable in the settings page.

Thanks for sharing your idea and the link. It's implemented in my fork.
Tests and feedback welcome.
If you have heating+cooling device: then we need to figure it out together. currently only heat-device implemented.

Folke

**Pull request closed without merging**
